version: '2.2'
services:
  ballista-standalone:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime-stage
      args: 
        BIN_NAME: standalone
    ports:
      - 50050:50050
      - 50051:50051
    environment:
      - RUST_LOG=info
      - BALLISTA_STANDALONE_EXECUTOR_EXTERNAL_HOST=ballista-standalone
    volumes:
      - ../data:/data
  ballista-executor:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime-stage
      args: 
        BIN_NAME: executor
    ports:
      - 50052:50051
    environment:
      - RUST_LOG=info
      - BALLISTA_EXECUTOR_SCHEDULER_HOST=ballista-standalone
      - BALLISTA_EXECUTOR_SCHEDULER_PORT=50050
    volumes:
      - ../data:/data
    depends_on:
      - ballista-standalone
  ballista-client:
    image: ballista:0.5.0-SNAPSHOT
    command: "/tpch benchmark ballista --host ballista-standalone --port 50050 --query 1 --path /data --format tbl"
    environment:
      - RUST_LOG=info
    volumes:
      - ../data:/data
    depends_on:
      - ballista-standalone

