[general]
name = "Ballista Executor"
env_prefix = "BALLISTA_EXECUTOR"
conf_file_param = "config_file"

[[param]]
name = "scheduler_host"
type = "String"
doc = "Scheduler host"

[[param]]
name = "scheduler_port"
type = "u16"
default = "50050"
doc = "scheduler port"

[[param]]
name = "bind_host"
type = "String"
default = "std::string::String::from(\"0.0.0.0\")"
doc = "Local IP address to bind to."

[[param]]
name = "bind_port"
type = "u16"
default = "50051"
doc = "bind port"

[[param]]
name = "cluster_name"
type = "String"
doc = "Fargate cluster name"
optional = false

[[param]]
name = "scheduler_task_def_arn"
type = "String"
doc = "Task Definition ARN for scheduler component (standalone task)"
optional = false
