[general]
name = "Ballista Executor"
env_prefix = "BALLISTA_EXECUTOR"
conf_file_param = "config_file"

[[switch]]
name = "version"
doc = "Print version of this executable"

[[param]]
name = "scheduler_host"
type = "String"
default = "std::string::String::from(\"localhost\")"
doc = "Scheduler host"

[[param]]
name = "scheduler_port"
type = "u16"
default = "50050"
doc = "scheduler port"

[[param]]
name = "bind_host"
type = "String"
default = "std::string::String::from(\"0.0.0.0\")"
doc = "Local IP address to bind to."

[[param]]
name = "bind_port"
type = "u16"
default = "50051"
doc = "bind port"
