[general]
name = "Ballista Standalone = Scheduler + Executor"
env_prefix = "BALLISTA_STANDALONE"
conf_file_param = "config_file"

[[param]]
name = "namespace"
type = "String"
doc = "Namespace for the ballista cluster that this executor will join. Default: ballista"
default = "std::string::String::from(\"ballista\")"

[[param]]
name = "bind_host"
type = "String"
default = "std::string::String::from(\"0.0.0.0\")"
doc = "Local host name or IP address to bind to. Default: 0.0.0.0"

[[param]]
name = "scheduler_bind_port"
type = "u16"
default = "50050"
doc = "scheduler bind port. Default: 50050"

[[param]]
name = "executor_bind_port"
type = "u16"
default = "50051"
doc = "executor bind port. Default: 50051"

[[param]]
name = "executor_external_host"
type = "String"
doc = "Host name or IP address to register with scheduler so that other executors can connect to this executor. If none is provided, the scheduler will use the connecting IP address to communicate with the executor."

[[param]]
name = "task_expiration_sec"
type = "i64"
default = "600"
doc = "The number of seconds without requests after which the scheduler shuts down"

[[param]]
name = "concurrent_tasks"
type = "u16"
default = "1"
doc = "The number of parallel tasks that can run on this executor"
