# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[general]
name = "Ballista Standalone = Scheduler + Executor"
env_prefix = "BALLISTA_STANDALONE"
conf_file_param = "config_file"

[[switch]]
name = "version"
doc = "Print version of this executable"

[[param]]
name = "namespace"
type = "String"
doc = "Namespace for the ballista cluster that this executor will join. Default: ballista"
default = "std::string::String::from(\"ballista\")"

[[param]]
name = "bind_host"
type = "String"
default = "std::string::String::from(\"0.0.0.0\")"
doc = "Local host name or IP address to bind to. Default: 0.0.0.0"

[[param]]
name = "scheduler_bind_port"
type = "u16"
default = "50050"
doc = "scheduler bind port. Default: 50050"

[[param]]
name = "executor_bind_port"
type = "u16"
default = "50051"
doc = "executor bind port. Default: 50051"

[[param]]
name = "executor_external_host"
type = "String"
doc = "Host name or IP address to register with scheduler so that other executors can connect to this executor. If none is provided, the scheduler will use the connecting IP address to communicate with the executor."
